modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/corelib/issues"
[[mods]]
modId = "corelib"
version = "${mod_version}"
displayName = "Corelib"
displayURL = "https://github.com/henkelmax/corelib"
authors = "Max Henkel"
description = '''A shared library'''
[[dependencies.corelib]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.corelib]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"