modLoader="javafml"
loaderVersion="${mod_forge_version}"
issueTrackerURL="https://modrepo.de"
displayURL="https://modrepo.de"
# logoFile="corelib.png"
# credits=""
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_vendor}"
# updateJSONURL=""
description=''''''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"