modLoader="javafml"
loaderVersion="${mod_forge_version}"
license="All rights reserved"
issueTrackerURL="https://modrepo.de"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
# updateJSONURL=""
displayURL="https://modrepo.de"
# logoFile="corelib.png"
# credits=""
authors="${mod_vendor}"
description=''''''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"